name: test
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['^1.13', '^1.14']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          # Required by Fyne
          sudo apt install libgl1-mesa-dev xorg-dev
      - name: Test
        run: go test -v -race ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          # Required by Fyne
          sudo apt install libgl1-mesa-dev xorg-dev
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/bin v1.27.0
      - name: Run golangci-lint
        run: ~/bin/golangci-lint run --out-format github-actions
