name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go: ['1.13.x', '1.14.x']
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v -race ./...
